### ISSUE TITLE
Ascertain password reset works

### ISSUE THREAD

**Issue by maverickwoo** [picoCTF/picoCTF#131]
We want to check the status of this feature. At the moment, there appears to be at least some missing configuration. (It doesn't work with just `vagrant up`.)

**Comment by sdlinn** [comment]
Awaiting completion of #21

**Comment by carlislemc** [comment]
See https://github.com/picoCTF/picoCTF/pull/138

**Comment by hiliang-cmu** [comment]
Checking in real quick, has this been tested? The email arrives from email fixes, but I  believe a change to nginx config needs to be made, as the `/reset` page is currently and incorrectly being checked for login first.
