### ISSUE TITLE
nginx/uwsgi PHP header() function not working

### ISSUE THREAD

**Issue by emonte02** [picoCTF/picoCTF#133]
Hello,

I run a CTF in a custom built box and I'm trying to migrate my challenges to the hacksport/pico platform. One of my challenges hides the flag in a custom HTTP response header "Flag: flag{blahblah}".

The challenge loads fine, but it looks like uwsgi strips all response headers except for "Encoding".

is this by design? is there a way to allow PHP to issue custom response headers?

I'm attaching the challenge .deb file.
[fiu-hypertext-transfer-p1-0-0.deb.zip](https://github.com/picoCTF/picoCTF/files/2238910/fiu-hypertext-transfer-p1-0-0.deb.zip)

Let me know if you need any more info.

**Comment by hiliang-cmu** [comment]
nginx strips out headers with certain characters in it, it seems to be catching your brackets. I modified the problem to just `flag:{{flag}}` and it worked.
