### ISSUE TITLE
competition_name and competition_urls incorrectly configured

### ISSUE THREAD

**Issue by jingjiey** [picoCTF/picoCTF#139]
These are not defined in config.py and this was causing email.py to break [here](https://github.com/picoCTF/picoCTF/blob/45112c52b33a44305e3c8210cf7c23a0b1d695ea/picoCTF-web/api/email.py#L77) 
This causes further issues when exceptions are thrown in logger.py [here](https://github.com/picoCTF/picoCTF/blob/45112c52b33a44305e3c8210cf7c23a0b1d695ea/picoCTF-web/api/logger.py#L160)

PR #138 fixes this by adding this to the CTF settings and the Management tab of the admin configuration page

**Comment by carlislemc** [comment]
See https://github.com/picoCTF/picoCTF/pull/138
