### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by al3xfulton** [picoCTF/picoCTF#143]
When working with the framework for a while it will seemingly randomly give memory errors on ```sudo shell_manager package xxxx``` which will persist until things will eventually free up (generally around 3-4 minutes later). When opening up ps aux it shows many (at least 40-50) sets of the following entry:

```
vagrant   6819  0.0  0.9 146620 19348 ?        S    02:49   0:00 sshd: vagrant@notty
root      6836  0.5  0.9 146620 18524 ?        Ss   02:50   0:01 sshd: vagrant [priv]
```

**Comment by carlislemc** [comment]
Can you do top when this happens?

**Comment by maverickwoo** [comment]
@al3xfulton I have seen a similar situation happening on my test VMs. Based on watching `htop` on the VMs, I think this could be due to `/picoCTF-env/bin/python3.6 /picoCTF-env/bin/daemon_manager -d /picoCTF/picoCTF-web/daemons cache_stats share_instances` running on the *web* server.
