### ISSUE TITLE
Re-enable mongodb indexing

### ISSUE THREAD

**Issue by hiliang-cmu** [picoCTF/picoCTF#151]
https://github.com/picoCTF/picoCTF/blob/571e8d52556ad703667dac57197ca7e30ef7baed/picoCTF-web/api/setup.py#L10

This sets up a number of indexes that would impact performance, but was disabled at some point: 

https://github.com/picoCTF/picoCTF/blob/571e8d52556ad703667dac57197ca7e30ef7baed/picoCTF-web/api/__init__.py#L29

According to pymongo documentation, `ensure_index()` has been deprecated as of v3.0

Should figure out proper way to re-enable indexes. Maybe hook into first admin account designation, rather than check exists-else-create indexes every initialization.

**Comment by hiliang-cmu** [comment]
According to pymongo documentation, `ensure_index()` has been deprecated as of v3.0

**Comment by maverickwoo** [comment]
What is the status of this issue? I seem to recall we have discussed this in person but I don't recall the resolution. :>

**Comment by hiliang-cmu** [comment]
e0bcf471c295b51a15b302c94c01bb256e7ce81a on -2018 added it in as short term solution

**Comment by hiliang-cmu** [comment]
Above course of action taken in f23ef80fa923dcd9c8a9d5988a58594635345d8f
