### ISSUE TITLE
Consider banning underscore from username

### ISSUE THREAD

**Issue by maverickwoo** [picoCTF/picoCTF#158]
Remotely related to #49 (what username to prohibit, e.g., `root`), we should consider banning underscore from the usernames. Assuming the current problem naming convention (`{{problem-name}}_{{instance numeric}}`), this will guarantee that no one can register a username that collides with problem usernames.

**Comment by hiliang-cmu** [comment]
Only alphanumerics allowed :)

https://github.com/picoCTF/picoCTF/blob/bafd28cce2241e978e3c1ad32e2ca7eb57a2b66d/picoCTF-web/api/user.py#L22

**Comment by maverickwoo** [comment]
Ah, perfect! (Sorry for my confusion! :>)
