### ISSUE TITLE
copy/paste out of webshell

### ISSUE THREAD

**Issue by al3xfulton** [picoCTF/picoCTF#159]
currently copy/paste does not work, tested on ubuntu 18.04 and firefox 61.0.1

**Comment by maverickwoo** [comment]
Note to future: Look into https://xtermjs.org/ and related projects.

**Comment by maverickwoo** [comment]
Upon more investigations, here is my current theory on what I think should work in the terminal in the "Shell" tab. If confirmed, we can put this instruction on the page.

- **Copy:** Select some text in the terminal, then press Ctrl-c (or Cmd-c on macOS). The selected text should get into the system clipboard.

(Note: Selecting "Copy" in the context menu from right-clicking would _not_ copy the text to the system clipboard. The text only goes into a clipboard variable inside the terminal, which you can then paste back into the terminal using the "Paste" command in the context menu.)

- **Paste:** Right-click in the terminal to show the context menu, select "Paste from browser", paste from the system clipboard into the browser dialog box (Ctrl-v or Cmd-v), then press enter to confirm. The pasted text should get into the terminal.

Can you please see if these two both work for you in Linux?

Tested platforms (every browser listed here is the latest on its respective platform as of this writing, though my macOS is behind):
- Windows 10: Chrome 69, FireFox 62, Edge 42
- macOS 10.9: Chrome 67, FireFox 62, Safari 9.1
- Chromebook: Chrome 68

**Comment by al3xfulton** [comment]
I have verified on an updated macOS 10.13: Firefox 63(b), Chrome 68 and Ubuntu 18.04: Firefox 60 that both of the above statements hold true (and additionally the copying from the dropdown does not go to the system clipboard). It would appear that it would be safe to put something about this on the page.

**Comment by maverickwoo** [comment]
I issued a PR for this already, but I am here to leave a note that "Cmd+V/Ctrl-V" actually works in Chrome but not in Firefox in my tests. Thus, the instruction never mentions this key combo.

(The effect of pressing Cmd+V in Firefox for me is sending `v` to the terminal.)
