### ISSUE TITLE
Consider defaulting `obfuscate_problem_directories` to true

### ISSUE THREAD

**Issue by maverickwoo** [picoCTF/picoCTF#160]
We should investigate why this setting currently defaults to false. And if there is no good reason, we may as well default it to true because it seems like a desirable feature to have in *any* deployment.

https://github.com/picoCTF/picoCTF/blob/43b5a46333c4ca57a762830248e04bceedefa5a5/ansible/roles/pico-shell/templates/config.json.j2#L15

https://github.com/picoCTF/picoCTF/blob/1806f066813f28e1c9f68e6166d5d46d63bc0daa/picoCTF-shell/shell_manager/util.py#L63-L65

**Comment by hiliang-cmu** [comment]
Without having dug into it, adding note that one of the web daemons connects to the shell server(s) to symlink problem directories from each player's home dir. Should ensure that remains compatible
