### ISSUE TITLE
teacher account can't create class

### ISSUE THREAD

**Issue by carlislemc** [picoCTF/picoCTF#169]
Tried with accounts thedoctor3 and thedoctor4 at picoctf.com

**Comment by hiliang-cmu** [comment]
This is on high priority list, currently there is not clear distinction between "teacher" and "admin" user types.   Soon as that's clearly delineated, teachers will have that feature enabled.

**Comment by maverickwoo** [comment]
Addressed by #181 (merged).

**Comment by maverickwoo** [comment]
Actually, this issue is only closed from the perspective of the 2018 deployment because the private repo has a different registration form. For this open-source edition, currently there is still no way to register as a *non-admin teacher*.

**Comment by dmartin** [comment]
Resolved by #255
