### ISSUE TITLE
Adjust ansible so that jekyll build runs on a local copy

### ISSUE THREAD

**Issue by maverickwoo** [picoCTF/picoCTF#186]
We seems to be hitting the null-bytes-in-output https://github.com/jekyll/jekyll/issues/5035 a lot. This should be two easy ansible modifications: add a task to copy the `picoctf-web` to home and then run jekyll from there instead.

**Comment by hiliang-cmu** [comment]
Will continue to keep an eye on this, but using a non-mounted drive should address the issue.
