### ISSUE TITLE
After reprovisioning the webshell rejects logons

### ISSUE THREAD

**Issue by al3xfulton** [picoCTF/picoCTF#189]
After pulling most recent branch and re-provisioning both shell and web, everything appears to work correctly except for login on the webshell. After the update the correct passwords (which work on the web login still) no longer work for the shell.

**Comment by al3xfulton** [comment]
Resolved by re-provisioning with correctly set WIP and SIP values.

**Comment by maverickwoo** [comment]
Note for future: this is related to #155 (Persist overridden settings)
