### ISSUE TITLE
Contact LASACTF?

### ISSUE THREAD

**Issue by percontation** [picoCTF/picoCTF#20]
Dunno if they've already contacted y'all, but http://lasactf.com seemed to be having a security issue with the picoCTF framework, so someone should reach out to them and figure out if there's anything that should be fixed.

**Comment by royragsdale** [comment]
HI @percontation, thank you for the heads up. The had not contacted us be we are reaching out now. We really appreciate the notification.

**Comment by royragsdale** [comment]
For continuity sake the issue is believed to have been https://github.com/picoCTF/picoCTF-shell-manager/issues/81, with a temporary merged fix in https://github.com/picoCTF/picoCTF-web/commit/f0fab2f08513811e30d5e7e36e2370cd3a893183
