### ISSUE TITLE
Way to install packages to be used in challenge.py

### ISSUE THREAD

**Issue by LiptonB** [picoCTF/picoCTF#214]
It appears that python packages referenced in `pip_requirements` or in `requirements.txt` are installed to the system python directories via the postinst script. However, `challenge.py` is imported by shell_manager, which runs in the `/picoCTF-env` virtualenv, so it doesn't have access to system packages. Is there any way to install packages that will be available for import in `challenge.py`?

This appears to be alluded to in https://github.com/picoCTF/picoCTF/issues/108#issuecomment-405380468, but I don't understand the full context of those remarks (can't figure out what "@zaratec's issue" refers to). Feel free to close this as a duplicate if this is already part of the scope of that issue.

**Comment by hiliang-cmu** [comment]
In our 2018 deployment we ended up manually adding a select few packages required by `challenge.py` directly into the `setup.py` for `api` module. You're correct in that it's currently not well supported.

This was indeed the same issue in the #108 comment. I'm adding a quick update to that issue shortly.
