### ISSUE TITLE
Add generous CPU limit to problem-users

### ISSUE THREAD

**Issue by maverickwoo** [picoCTF/picoCTF#218]
We currently enforce CPU limit on competition users using cgroup. We should consider using the same mechanism to prevent our own problem-users overwhelming the CPU. For example, we can cap all the problem-users *in total* to be no more than 98%. (This way the machine stays somewhat responsive and still can be used to full capacity to run the problem instances.)

**Comment by hiliang-cmu** [comment]
This should be resolved for 2019 launch

**Comment by hiliang-cmu** [comment]
Is there any issue for problem users to be in a `problems` group?

**Comment by hiliang-cmu** [comment]
After some digging: 

https://github.com/picoCTF/picoCTF/blob/3ef248dcbca4928094af332145651cec77d15d70/ansible/roles/pico-shell/files/pam_session.py#L114

At moment *all* users, including problem instance users are covered under `user.slice` with overall limit of 90% CPU shares. Combined with `cpu` limit, this should ensure that 1) nothing leads to system unresponsiveness and 2) anything running particularly long will end up killed anyhow.
