### ISSUE TITLE
allow teachers to register student accounts (suggestion for 2019)

### ISSUE THREAD

**Issue by carlislemc** [picoCTF/picoCTF#221]
From a teacher : " As a suggestion for future years, it would be great if teachers could create their class account and then register the students through the teachers login without requiring student information. I think you would have more participation among schools if less information was required from students and there were a way to avoid the need for a confirmation email from the students. 

Since we deal with minors, information is very sensitive. Especially where we are trying to teach them safe online practices, it is somewhat ironic that they cannot participate in this program unless they give up personal information. I know it doesn’t seem like you are asking for a lot of info, but I am bound by the rules and laws of my state and district. 

Im just trying to follow the laws and rules I’ve been given. Thanks again for this program and the efforts you are making. I think it is fantastic."

**Comment by syreal17** [comment]
Do you think it's reasonable to be concerned about an attacker abusing an implementation of this suggestion?

**Comment by carlislemc** [comment]
We might consider a cap, but someone could automate registering single accounts as is.

**Comment by hiliang-cmu** [comment]
> We might consider a cap, but someone could automate registering single accounts as is.

We do have captcha so it's a bit throttled. Perhaps we just have a request system and we (admins) can generate them after brief approval.
