### ISSUE TITLE
students with too many processes can't kill them

### ISSUE THREAD

**Issue by carlislemc** [picoCTF/picoCTF#225]
Many students have gotten into this issue with tmux. We should think about a way a user can kill all their processes if they lock themselves out of the shell.

**Comment by maverickwoo** [comment]
It's a configuration problem and we will fix it in `/etc/security/limits.conf`. For now, you will have to adjust `nproc` and `maxlogins` manually.

Note: If we set `nproc` to be `N`, then we should set `maxlogins` to `N-2` (one to discount `sshd` and one for the multiplexer). Right now the settings are `40` and `10` respectively, and therefore it is quite easy to get into a state where more processes are created before detach, and then there is no way to login any more...

**Comment by maverickwoo** [comment]
I see this has been fixed in d889355. Thanks!
