### ISSUE TITLE
Refactor ansible scripts into api_manager

### ISSUE THREAD

**Issue by royragsdale** [picoCTF/picoCTF#23]
Currently the ansible configuration resorts to a few scripts in order to automate the configuration of a competition [scripts](https://github.com/picoCTF/picoCTF/tree/7db3e8028a9520565841a933a908bea15361ac1d/ansible/scripts).  These would be much better suited if they were added to the [api_manger](https://github.com/picoCTF/picoCTF/blob/master/picoCTF-web/api/api_manager.py).

**Comment by dmartin** [comment]
`api_manager` is no longer present/used in recent builds, closing this for now
