### ISSUE TITLE
1GB is too little for the Web VM

### ISSUE THREAD

**Issue by maverickwoo** [picoCTF/picoCTF#249]
As of this writing, starting the Web VM with its default setting (1GB RAM) would yield an unstable VM that can thrash. A workaround until we change the default in `Vagrantfile` would be to start the VM by overriding the `M` env var to give the VM more memory, e.g., `M=2 vagrant up web`.

**Comment by maverickwoo** [comment]
More investigations later, I found out that the issue I observed was due to a different checkout and that checkout just wasn't designed to work with 1GB of RAM in the web vm. Therefore, I am closing this issue.

**Comment by hiliang-cmu** [comment]
As a note, the 18.04 LTS branch with imported database and problems from 2018 competition strained and at times failed w/ the memory allocation of 1GB, but runs fine at 2GB. I bumped the baseline config to 2GB, as I think that simulating a real production load should be doable out of the box.
