### ISSUE TITLE
Ansible should fail early by checking shell script corruption due to autocrlf

### ISSUE THREAD

**Issue by maverickwoo** [picoCTF/picoCTF#250]
I propose we add an ansible step to in the very beginning of provisioning to check if one of our shell scripts is corrupted due to autocrlf. The step should cause a fatal error so that the rest of the provisioning is stopped.

For context, we routinely run into Windows users who could not follow the clone command we spelled out. This is understandable. However, the failed provisioning is too subtle for a first-time user to discern. Having this step should make the failure (and its cause) very obvious.

**Comment by syreal17** [comment]
Clarification: what is the end state of the doomed/would-be picoCTF deployer as you have observed when they do:
`C:\Windows\System32> git clone https://github.com/picoCTF/picoCTF.git
C:\Windows\System32> vagrant up` ?

I'm curious if anyone has ever complained to you about this?

Our best hope for having shell scripts interact with Windows is WSL, however, [HashiCorp claims that WSL support in Vagrant is beta](https://www.vagrantup.com/docs/other/wsl.html), and from the scant documentation on the subject, it seems more like pre-alpha.

I think @hiliang-cmu has managed to deploy picoCTF on Windows (correct me if I'm wrong) so he might have more insight.

For me, deploying picoCTF on the macMini was as easy as following the instructions in the readme. But deploying picoCTF on my personal Windows gaming rig required much more than is currently in the readme, and I even heeded the autocrlf git step from the beginning.

**Comment by maverickwoo** [comment]
#68 is the earliest known complaint and you can see the output. Prior to seeing that issue, I myself never had encountered that problem because my git on windows has always had autocrlf disabled. The goal of this PR is so that a similar user as in #68 would:
1. observe the clone failure early: ansible should abort once it detects a likely-designated shell script has the wrong line ending.
2. observe the clone failure clearly: ansible should fail "loudly", meaning part of the ansible error message should tell the user what they did wrong.

BTW, we are not trying to have the Unix shell scripts running *inside* Windows. It seems unlikely that @hiliang-cmu would be running the picoCTF platform on top of WSL without further virtualization. I would guess he just meant `vagrant up` works inside WSL. (And that may very well be the case because the git shipped inside WSL likely does not enable autocrlf by default.)

Finally, regarding your Windows rig, let's bring it in and take a look (and move the discussion to in-person). For me, the Quick Start instructions worked perfectly well on a fresh Windows 10 laptop of mine so long as the clone command disable autocrlf.

**Comment by syreal17** [comment]
Let's just enforce correct line endings in the root special file ".gitattributes" ...

It overrides per-user "core.autocrlf" settings, and seems to solve this issue well . See: [Dealing with Line Endings - GitHub Help](https://help.github.com/en/articles/dealing-with-line-endings).

That way anyone can just do the usual `> git clone https://github.com/picoCTF/picoCTF.git` and get the right stuff.

**Comment by maverickwoo** [comment]
Can you please propose a `.gitattributes` in a comment for discussion? Thanks!

**Comment by syreal17** [comment]
Of course!

I know the final error state is a bit weird, but do you have an idea of what files from the clone are being corrupted with bad line endings?

**Comment by maverickwoo** [comment]
I don't have any idea other than I know the shell scripts are corrupted. However, I can think of two methods to investigate:

1. The easy but time-consuming method would be to use a Windows machine/VM to get a list of checksums to compare.

2. A much faster way is to realize that the set of files will be (almost by definition) "every file that is considered 'text' by git". A bit of search taught me that we can figure this out with `git grep -I --name-only --untracked -e . -- .`. There appears to be 355 files in my working directory.

P.S. When you are coming up with your `.gitattributes`, please also be aware that you may eventually uncover strong reason(s) why `.gitattributes` may be a wrong solution to the autocrlf problem (especially after you see the list of files in 2. above.)

**Comment by syreal17** [comment]
Some other helpful resources on this issue: [1. GitHub developer blog on the history and current status of the line ending problem](https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/) and [2. Web man page on gitattribute file](http://schacon.github.io/git/gitattributes.html)

My summary: the line ending problem has a long history for code repositories. The old solution was per-user, utilizing options like `core.autocrlf`. The new solution is per-repo, by a `.gitattributes` that overrides per-user settings for files in the repo.

```picoCTF$ cat .gitattributes
# This is a catch-all that overrides per-user options like 'autocrlf' 
# but also relies on git's heuristic detection of textual files. Git does
# well at this detection except for files that contain both text and 
# binary blobs, or data that is readable but really meant to be opaque
*    text=auto

# Here are some examples of overriding Git auto-detection
*.png   binary
*.tf    text eol=lf
*Vagrantfile text eol=lf  # obviously not based on extension, but still low-hanging fruit
```
Is your misgivings about scripts that do not follow a naming convention?

**Comment by maverickwoo** [comment]
Putting any misgivings about using `.gitattributes` to solve this problem aside, my suggestion (https://github.com/picoCTF/picoCTF/issues/250#issuecomment-473038779) is to first come up with a `.gitattributes` that you have reasons to believe would mitigate the error for (primarily) Windows users, i.e., if our git repo has your proposed `.gitattributes`, then a user who has `core.autocrlf` set to `true` would clone correctly using `git clone https://github.com/picoCTF/picoCTF.git`. Is the `.gitattributes` in https://github.com/picoCTF/picoCTF/issues/250#issuecomment-473342601 the proposal?

**Comment by carlislemc** [comment]
Ok, so (on Windows) I installed GIT Bash, Vagrant and VirtualBox, then did a git clone of https://github.com/syreal17/picoCTF  (latest commit  9b631d2). I did make sure core.autocrlf was set to true via git config --get core.autocrlf. Everything seemed good and I was able to visit the website.

**Comment by maverickwoo** [comment]
@carlislemc Hmm, that's curious. I have two questions about your git clone and your test deployment:

1. What is the file size of `/mkdeploy.sh` in the work tree? 4988 (this would indicate the file is in LF) or 5146 (CRLF)?
2. In your test deployment, do you see the three sample problems?

P.S. By my calculation, using the `.gitattributes` in 9b631d2 with `*    text=auto`, a clone with `core.autocrlf=true` would yield a `/mkdeploy.sh` with CRLF (so the size would be 5146), the deployed VMs would boot (even though the clone was in CRLF), you would also be able to register the admin account successfully, but the three sample problems would not be there because the provision would have actually failed (but the error message was too subtle to notice).

**Comment by carlislemc** [comment]
Size is 5146. I didn't check to see if the problems deployed but destroyed the VMs. I can run it again if you really need to know.

**Comment by maverickwoo** [comment]
Thanks! 5146 is the CRLF file size and that's good enough to confirm that the `.gitattributes` in 9b631d2 is a nice first try but not the final answer. (I won't suggest creating the VMs to confirm anything. If the checkout was in CRLF, the problems won't be there last time I actually checked.)

Your experience actually backs up my original intent when creating this issue: the provision failed in such a subtle manner that we should not expect anyone to be able to notice the failure.

**Comment by carlislemc** [comment]
https://www.git-scm.com/docs/gitattributes seems to suggest a different solution for this -- "Here is an example that will make Git normalize .txt, .vcproj and .sh files" or perhaps one could simply do:
[core]
	autocrlf = false
Doing the former seems to allow me to get through vagrant up with no visible issues (warnings/errors), but still no problems loaded.
