### ISSUE TITLE
Add coverage testing

### ISSUE THREAD

**Issue by syreal17** [picoCTF/picoCTF#277]
By adding automatic testing to picoCTF, we would want some metric to know how much of our code is currently being tested by automatic means.

**Comment by syreal17** [comment]
Thanks @sven-schl! Maybe it'd be good to link your own repo demonstrating codecov? I think it's helpful to see it in action.

**Comment by sven-schl** [comment]
@syreal17 no problem
Here is the link to the test repository: https://github.com/sven-schl/travis-test
To see Travis-CI and Codecov in action, take a look at pull request 4: https://github.com/sven-schl/travis-test/pull/4

It's not a perfect configuration yet, but a good starting point.

**Comment by dmartin** [comment]
Since we have codecov set up, I think this issue can be considered complete.
