### ISSUE TITLE
Perform load testing

### ISSUE THREAD

**Issue by syreal17** [picoCTF/picoCTF#278]
Esp. if we add portal-esque features, we need to test our servers' ability to handle the traffic. Having evidence that our servers can handle large volumes of traffic will help mitigate the need to throw money at infrastructure, although load testing will never completely accurately predict real traffic.

**Comment by syreal17** [comment]
As a note, @dmartin has suggested that performing load testing might help us diagnose what queries are slowing down Web performance.

Some professional tools available are: JMeter, Locust, Gatling, though even just writing a custom Python driving hitting the Web API might be simpler and more direct (esp. for diagnosing db lag)

**Comment by dmartin** [comment]
Locust tests in #383 serve as a starting point for load testing common user actions
