### ISSUE TITLE
User management in admin dashboard

### ISSUE THREAD

**Issue by dmartin** [picoCTF/picoCTF#312]
Provide a pane in the admin dashboard view to support basic user management operations without accessing the database directly.

- Search for user by username/email/parent email
- Delete (disable) user account

**Comment by maverickwoo** [comment]
We may also consider handling basic team-related queries, e.g.,
- which team is a user in
- who are the members of a team

**Comment by syreal17** [comment]
> * Delete (disable) user account

@archituiet is working on a PR that resolves #267 which is strongly related to quoted item from @dmartin 's list
