### ISSUE TITLE
Discuss new naming convention for problem directories on shell server

### ISSUE THREAD

**Issue by syreal17** [picoCTF/picoCTF#314]
For example, in the 2018 problem set:
> Reversing Warmup 1 - Points: 50
> Throughout your journey you will have to run many programs. Can you navigate to **/problems/reversing-warmup-1_4_6b2499250c4624337a1948ac374c4934** on the shell server and run this program to retreive the flag?

Thankfully @dmartin's update to our provided browser shell makes these folder names less of an issue (b/c seamless copy and paste), but I still think we could do better.

If anyone cares to comment:
* Why do we tack what looks like a hash on the end of the problem name for the folder?
* Why is the hash so long? (last five digits would seem more than sufficient)

I believe the naming convention could be improved by:
* More clarity that this file is a directory
* Pseudorandomness that works with command-line auto-complete

I would like to change folder names to something like:
> **/problems/reversing-warmup-1_4_directory_alpha_beta**

**Comment by hiliang-cmu** [comment]
Re hashed sir: From memory, had to do with intent to obscure names of different instances and problems to not be guessable

**Comment by carlislemc** [comment]
Yes @hilang-cmu is correct. It is configurable to turn off the long hashes.

**Comment by syreal17** [comment]
@hiliang-cmu @carlislemc nice, glad it already has something for easier access to directories.

I'm going to dub these "cryptographically secure directory names." I'm guessing this novel approach was adopted because it protects access to directories without need to set or manage permissions. It strikes me as an expedient solution, though highly unusual.

I think it's far from most important right now, but I think our participants would benefit a lot from our shell server being navigable like most normative Linux servers and if sensitive resources were protected using permissions instead of cryptographically secure directory names.

**Comment by hiliang-cmu** [comment]
In separate issue from this one, we should revisit the problem directory symlinking function (which was performed via a daemon, but disabled in 2018). In some ideal world, a neat set of symlinks should exist in each home directory to the respective hashed directories.

**Comment by syreal17** [comment]
@hiliang-cmu Ah ok. That would help.

Do you think that using permissions instead of secret directory names would be too difficult to be worth it?
