### ISSUE TITLE
Verbiage incorrect in web unit test

### ISSUE THREAD

**Issue by syreal17** [picoCTF/picoCTF#321]
Found by investigating Travis CI failure for PR #320. It seems we missed the Travis failure for when this string was originally changed in I'm guessing PR #315

We've changed the wording of the [user account gone] message, so web unit tests have falsely failed. Very trivial fix, but I'm about to go on a conference call, etc.

Full Travis CI job here: https://travis-ci.com/picoCTF/picoCTF/jobs/209745529

In particular, these lines of the log:
```
        # Force-disable account and attempt to login
        db = get_conn()
        db.users.update({'username': USER_DEMOGRAPHICS['username']},
                        {'$set': {'disabled': True}})
        res = client.post('/api/v1/user/login', json={
            'username': USER_DEMOGRAPHICS['username'],
            'password': USER_DEMOGRAPHICS['password']
        })
        assert res.status_code == 403
        assert res.json['message'] == 'This account has been disabled.'
E       AssertionError: assert 'This account...been deleted.' == 'This account ...een disabled.'
E         - This account has been deleted.
E         ?                        ^ --
E         + This account has been disabled.
E         ?                        ^^^^
tests/api/functional/v1/test_user.py:54: AssertionError
```

Trivial fix is to hard code the currently correct message. Comprehensive solution is for code to all grab strings from a centralized place. Whatever the solution, this should be fixed so that our web unit tests are not falsely failing.

**Comment by dmartin** [comment]
fixed this particular issue in #324, agreed that having a centralized location for strings would be an improvement though, both for this testing and potentially localization
