### ISSUE TITLE
Multiple users (100+) can register with same email ID

### ISSUE THREAD

**Issue by archituiet** [picoCTF/picoCTF#326]
The registration page on the test server (https://2019test1game.picoctf.com) allows multiple users to register using the same email id. I was able to create 100+ users (from Burp free Intruder) using email id as test@test.com with teacher and student roles each. Each registration request also results in verification mail sent to the email ID. [Brute Force / add several entries in DB?]

**Comment by dmartin** [comment]
Hmm, we could consider a reasonable limit on accounts/email address, but to some extent this is desired (e.g. registering many students under a teacher's email for batch registration)
Rate limiting (#223) might also make spam-registering many accounts less feasible

**Comment by hiliang-cmu** [comment]
There 2 things that should help:

1) Rate limiting as mentioned above
2) RECAPTCHA (as seen on 2018 live instance)
