### ISSUE TITLE
Web problems not responding

### ISSUE THREAD

**Issue by dmartin** [picoCTF/picoCTF#341]
For example, after starting up a local development environment with `vagrant up`, an instance of problem `sql-injection-1-0c436d0` should be available at `http://192.168.2.3:17648/`. However, no HTTP response is received on that port.

**Comment by syreal17** [comment]
I've labeled "priority:high" because this is blocking @kainny from testing the problems she has developed.

Alternatively, if this does not affect truer deployments, we could just load her problems on our live test server... @hiliang-cmu ?

**Comment by hiliang-cmu** [comment]
uwsgi won't startup properly due to permissions of `/tmp`, which has diverged somehow from `1773`. investigating why
