### ISSUE TITLE
nginx default page 

### ISSUE THREAD

**Issue by TGC-TECH** [picoCTF/picoCTF#444]
This is likely user error, but I am trying to follow your documentation as closely as possible, however I can never get to the page that allows me to create an admin account, instead I simple see the "you have installed nginx page" I am using vagrant with virtualbox on Ubuntu 16.04. Would be happy to provide any logs/system data you want/need. 

Thanks so much.

**Comment by hiliang-cmu** [comment]
Our 2019 release is based on Ubuntu 18.04, there may be packages that will not install correctly on a xenial VM. This should be done automatically by vagrant though, are you using the 2018 release?

**Comment by TGC-TECH** [comment]
Ok, that solves it, I am using the wrong release (I just cloned the main repo) I will try again with the 2018 release, or update to Ubuntu 18.04. Thanks for the clarification

**Comment by hiliang-cmu** [comment]
Closing assuming issue is resolved with proper vagrant box image
