### ISSUE TITLE
User cannot reset password if they do not remember capitalization

### ISSUE THREAD

**Issue by archang31** [picoCTF/picoCTF#456]
I had an issue with a user last week where they had an account, but they could not log in or reset their password because they did not remember their username capitalization. Below are the screenshots. There are many possible solutions to this issue - adding "get username" by matching email address, having the reset match without capitalization (since only can be one username with the same characters), or even just forcing all usernames lowercase in the database but saving a "display" value. I would think having the reset match without capitalization is probably the easiest/safest but leave the solution up to you as the experts.

Their actual username was `DmD`.

##### Step 1: Attempt Login
![image](https://user-images.githubusercontent.com/6031616/80381274-b6085180-886e-11ea-94c9-52d8dbba4437.png)

##### Step 2: Attempt Reset
![image](https://user-images.githubusercontent.com/6031616/80381282-bacd0580-886e-11ea-9e5e-13803b434dfd.png)

##### Step 3: Despair
![image](https://user-images.githubusercontent.com/6031616/80381628-362eb700-886f-11ea-9df8-4505639da975.png)

**Comment by dmartin** [comment]
Resolved w/ c13c901687ef92c848285a7adbe8743fecacbc22
