### ISSUE TITLE
API 404's not registered flask error handler

### ISSUE THREAD

**Issue by hiliang-cmu** [picoCTF/picoCTF#465]
Everything defaults to HTTP 500 (which is logged and clutters management console).

Maybe as simple as ?

```
@app.errorhandler(404)
def page_not_found(e):
        response = jsonify({"message": "API endpoint not found"})
        response.status_code = 404
        return response
```

**Comment by dmartin** [comment]
I think it really is that simple. Whoops. I remember meaning to fix this prior to 2019.
fixed w/ ed91cac
