### ISSUE TITLE
BUG: Listing users that have used the shell

### ISSUE THREAD

**Issue by iwillreku3206** [picoCTF/picoCTF#472]
I was looking around on the filesystem of the WeTTy shell (accessed from the Unity Game), and was able to get a list of users that have accounts on the shell

To do this, I just ran `ls` in `/home/`, giving me a list of users

**Comment by hiliang-cmu** [comment]
There are other ways to list users on v19 shell, including reading `/etc/passwd` and `/etc/group` 

This is the nature of having a shared shell environment.
