### ISSUE TITLE
Broken build (master & release-2019)

### ISSUE THREAD

**Issue by jrolli** [picoCTF/picoCTF#482]
Both `master` and `release-2019` branches currently have broken builds due to dependency conflicts on the `cryptography` package.  Specifically, `pyOpenSSL` has bumped their minimum version to 3.2 due to a security concern, but the shell server's `setup.py` still pins `cryptography` to 2.9.2.

The automated solution from #480 appears to fix this issue.

**Comment by dmartin** [comment]
Thanks, I had seen that dependabot PR hanging but hadn't had a chance to test it.
Updated `cryptography` references and also removed the `pyOpenSSL` dependency since nothing seems to actually require it anymore.
