### ISSUE TITLE
Vagrant/Ansible provisioning from Windows fails due to permission error

### ISSUE THREAD

**Issue by royragsdale** [picoCTF/picoCTF#53]
When the permissions for a synced folder are not specified in the Vagrantfile, windows defaults to 777 this causes challenge deployment to fail because dpk expects permissions  >= 755 and <= 775.

This can be most simple fixed by explicitly specifying mount options in the vagrantfile.

Another option would be to change the dpkg destination for building challenge .debs.

**Comment by zaratec** [comment]
Specifying synced folder permissions seems to work.
For example this line
```
shell.vm.synced_folder ".", "/picoCTF"
```
now with specified permissions
```
shell.vm.synced_folder ".", "/picoCTF",
    owner: "vagrant", group: "vagrant",
    mount_options: ["dmode=775","fmode=775"] 
```
works fine.

**Comment by carlislemc** [comment]
@zaratec - do you want to create a pull request and then we can close this?
