### ISSUE TITLE
Platform fails to properly restart after vagrant suspend

### ISSUE THREAD

**Issue by WilliamParks** [picoCTF/picoCTF#63]
Login page displays "The server is currently down. We will work to fix this error right away."

**Comment by zaratec** [comment]
Confirmed to be a recurrent issue when doing a `vagrant halt` - both Windows and Mac affected. Error text located at [dependencies.coffee](https://github.com/picoCTF/picoCTF/blob/2ba4374ada440427f67bfe50aafdbea2c63cbe32/picoCTF-web/web/coffee/dependencies.coffee). 

`vagrant up` then `vagrant provision` (or `vagrant up --provision`) seems to fix the issue. So something such as the server/API setup is only being done during provisioning. Unfortunately, provisioning takes several minutes as it tries to update/install things and then get to setting up whatever is needed. It may just be better to separate the two, as the update/install isn't needed every time, but the server/API(?) set up is.

**Comment by carlislemc** [comment]
@zaratec - thanks for discovering this workaround!

**Comment by carlislemc** [comment]
This appears to have been fixed by https://github.com/picoCTF/picoCTF/pull/98
