### ISSUE TITLE
vagrant fails because pip broken

### ISSUE THREAD

**Issue by carlislemc** [picoCTF/picoCTF#64]
Can workaround by:

run vagrant up
when it fails, log in to appropriate server and 
wget https://bootstrap.pypa.io/get-pip.py
sudo python3 get-pip.py

then:
ansible-playbook site.yml -i inventories/devploy --limit @site.retry

**Comment by maverickwoo** [comment]
@hiliang-cmu In the PR that you are preparing, can you please see if it also fixes this issue? (I think it does.)

**Comment by hiliang-cmu** [comment]
@carlislemc do you have any info on how pip broke back then? 

I was debating on updating pip to latest/10+ via the same bootstrap.pypa.io method as part of the OS and python upgrade, but held off as provisioning did not seem to have any problem with the xenial python3-pip package (8.1.1)

**Comment by maverickwoo** [comment]
For more context, I suspect that this issue had to do with a lack of python package pinning back then. So what happened was pip and setuptools (and other setup-related packages) were at some old versions, and one day in the past a package on pypi started depending on a newer version of one of these setup packages, thus failing to install.

You can see an error of this form in this commit:

https://github.com/picoCTF/picoCTF/commit/99aa9424f500dc40256e0665a1fef5ec1f250807

**Comment by carlislemc** [comment]
I do not have additional context to provide, but it appears that whatever pip was being installed wasn't good enough and I manually was installing pip from bootstrap.pypa.io to fix.

**Comment by hiliang-cmu** [comment]
The xenial upgrade https://github.com/picoCTF/picoCTF/commit/415533e56094d1a3f3985feab78997943d62587d provisions properly with pip 8.x from python3-pip.

If a python module starts breaking to where pip 10.0+ needs to be installed via https://bootstrap.pypa.io, can revisit this.
