### ISSUE TITLE
MongoDB install fails on AWS

### ISSUE THREAD

**Issue by saswatp** [picoCTF/picoCTF#69]
Hi , 

I got this error while running ansible as part of AWS deployment : 

failed: [remote_testing_db] => {"failed": true}
msg: No package matching 'mongodb-org' is available

FATAL: all hosts have already failed -- aborting

I am wondering if there is a pre-canned VM for web/db available that has software pre-installed, so that this kind of errors can be avoided. 

If not, Did anybody else face the same issue ? Do I have to update anything in apt or dpkg configurations ?

---- 

I am making resolution of remote_testing_db and remote_testing_web names in my /etc/hosts file. That is, map the elastic IP to the hostname in my mac. 

Thanks

**Comment by hiliang-cmu** [comment]
Given the use of a ppa's for mongodb from 2018 on, this should not be an issue. Upkeeping one or more AMI's does not seem a worthwhile effort at this time.
