### ISSUE TITLE
Challenge Creation/Deployment on Windows

### ISSUE THREAD

**Issue by veryredheaded** [picoCTF/picoCTF#72]
Is there an easy way to deploy challenges on Windows? 
All the commands provided at [Adding Your Own Content](https://github.com/picoCTF/picoCTF/wiki/Adding-Your-Own-Content) are Linux-based, of course, but I am struggling with adapting them to Windows... Any suggestions? :/

Thanks in advance!

**Comment by carlislemc** [comment]
You deploy challenges in the shell, which is a Linux VM.
