### ISSUE TITLE
shell_manager package breaks with newlines in description

### ISSUE THREAD

**Issue by jaybosamiya** [picoCTF/picoCTF#74]
Using a description like `"Break\nMaybe"` causes the package build process to break.

Partial Workaround: `"Break\n Maybe"` works (i.e., inserting a space right after the newline). However, this doesn't work if multiple `\n`s are used.

Even with the workaround however, no newlines are introduced in the web view of the challenge description. Not sure how to introduce newlines in the challenge description.

**Comment by maverickwoo** [comment]
Perhaps it would be better if `description` is a list of strings, with the understanding that each element of the list is a `<p>`?
P.S. For now I think using `<br>` would work. Can you try? Thanks!

**Comment by jaybosamiya** [comment]
Using `<br>` works. However, the list of strings thing is a good idea as well. For now, just using `<br>`.

Thanks :)

**Comment by carlislemc** [comment]
Fixed by https://github.com/picoCTF/picoCTF/pull/122
