### ISSUE TITLE
IP addresses in Vagrantfile does not auto-adjust

### ISSUE THREAD

**Issue by maverickwoo** [picoCTF/picoCTF#99]
This may not get fixed soon but I thought I should file an issue here to record it.

The issue is that https://github.com/picoCTF/picoCTF/blob/903400ab73b6dcfd27723476f8e472a12562b9a9/Vagrantfile#L13 hardcodes the IP address of the shell VM (and similarly for the web VM), and that makes the auto-naming of VMs in PR #90 almost dangerous.

This is because I test a PR using, for example, `git worktree add --track -b xenialbase ../picoCTF-xenialbase ivan/xenialbase`. With this command, the `Vagrantfile` in the new worktree uses the hardcoded IP addresses. However, `192.168.2.{2,3}` may have already been taken by the original pair of VMs (likely from `master`). So subsequent testing with the web browser on these two IP addresses will be testing the original pair of VMs and not the new pair.

Currently, the workaround is to suspend the original pair.

**Comment by carlislemc** [comment]
See https://github.com/picoCTF/picoCTF/commit/561a7add8544f9457ef910267fb321a1838d6e65
